version: "3.9"
name: qbittorrent-tailscale
services:
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    restart: unless-stopped
    network_mode: service:tailscale
    environment:
      - PUID=1026
      - PGID=100
      - TZ=${QBT_TZ}
    volumes:
      - ./qbittorrent/config:/config
      - ${QBT_MEDIA}:/media
  firefox:
    image: jlesage/firefox
    container_name: firefox
    restart: unless-stopped
    network_mode: service:tailscale
    shm_size: "2gb"
    environment:
      - USER_ID=1026
      - GROUP_ID=100
      - TZ=${QBT_TZ}
      - FF_PREF_PRIVATE=browser.privatebrowsing.autostart=true
    volumes:
      - ./firefox/config:/config
  tailscale:
    image: tailscale/tailscale:stable
    container_name: tailscale
    restart: unless-stopped
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_HOSTNAME=${TS_HOSTNAME}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/serve.json
      - TS_USERSPACE=false
      - TS_ACCEPT_DNS=true
      - TS_EXTRA_ARGS=--exit-node=${TS_EXIT}
      - TS_TAILSCALED_EXTRA_ARGS=--port=41642
    ports:
      - "41642:41642/udp"
    cap_add:
      - net_admin
    volumes:
      - ./tailscale/state:/var/lib/tailscale
      - ./tailscale/config:/config
    devices:
      - /dev/net/tun:/dev/net/tun
